# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pytype: skip-file
# pylint: disable=protected-access,g-import-not-at-top,unused-import
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: localharness.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12localharness.proto\x12\x18\x61ntigravity.localharness"\xfb\x01\n\x0bInputConfig\x12\x19\n\x11storage_directory\x18\x01'
    b' \x01(\t\x12\x0c\n\x04port\x18\x02'
    b' \x01(\r\x12\x1f\n\x0c\x62ind_address\x18\x03'
    b' \x01(\t:\tlocalhost\x12\x39\n\x0b\x63lient_info\x18\x04'
    b' \x01(\x0b\x32$.antigravity.localharness.ClientInfo\x12;\n\x03\x65nv\x18\x05'
    b' \x03(\x0b\x32..antigravity.localharness.InputConfig.EnvEntry\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"V\n\x1bInitializeConversationEvent\x12\x37\n\x06\x63onfig\x18\x01'
    b' \x01(\x0b\x32\'.antigravity.localharness.HarnessConfig"i\n\nClientInfo\x12\x10\n\x08language\x18\x01'
    b' \x01(\t\x12\x0f\n\x07version\x18\x02'
    b' \x01(\t\x12\x18\n\x10language_version\x18\x03'
    b' \x01(\t\x12\n\n\x02os\x18\x04 \x01(\t\x12\x12\n\nos_version\x18\x05'
    b' \x01(\t"\xac\x08\n\rHarnessConfig\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x62\n\x19session_continuation_mode\x18\x13'
    b' \x01(\x0e\x32?.antigravity.localharness.HarnessConfig.SessionContinuationMode\x12I\n\x13system_instructions\x18\x04'
    b' \x01(\x0b\x32,.antigravity.localharness.SystemInstructions\x12-\n\x05tools\x18\x05'
    b' \x03(\x0b\x32\x1e.antigravity.localharness.Tool\x12\x46\n\x12harness_side_tools\x18\x06'
    b' \x01(\x0b\x32*.antigravity.localharness.HarnessSideTools\x12\x1c\n\x14\x63ompaction_threshold\x18\x07'
    b' \x01(\r\x12\x37\n\nworkspaces\x18\x08'
    b' \x03(\x0b\x32#.antigravity.localharness.Workspace\x12\x14\n\x0cskills_paths\x18\t'
    b' \x03(\t\x12\x1f\n\x17\x66inish_tool_schema_json\x18\n'
    b' \x01(\t\x12\x1a\n\x12initial_trajectory\x18\x0b'
    b' \x01(\x0c\x12\x14\n\x0c\x61pp_data_dir\x18\x0c'
    b' \x01(\t\x12>\n\x0bmcp_servers\x18\x0e'
    b' \x03(\x0b\x32).antigravity.localharness.McpServerConfig\x12\x35\n\x06models\x18\x0f'
    b' \x03(\x0b\x32%.antigravity.localharness.ModelConfig\x12>\n\renabled_hooks\x18\x10'
    b" \x03(\x0e\x32'.antigravity.localharness.LifecycleHook\x12?\n\x10\x63ustom_subagents\x18\x11"
    b' \x03(\x0b\x32%.antigravity.localharness.CustomAgent\x12N\n\x16tool_output_truncation\x18\x12'
    b' \x01(\x0b\x32..antigravity.localharness.ToolOutputTruncation\x12;\n\x0cretry_config\x18\x14'
    b' \x01(\x0b\x32%.antigravity.localharness.RetryConfig"w\n\x17SessionContinuationMode\x12)\n%SESSION_CONTINUATION_MODE_UNSPECIFIED\x10\x00\x12\n\n\x06RESUME\x10\x01\x12\x14\n\x10\x43REATE_OR_RESUME\x10\x02\x12\x0f\n\x0b\x43REATE_ONLY\x10\x03*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\r\x10\x0e"\x83\x01\n\x13ModelAPIRetryConfig\x12\x13\n\x0bmax_retries\x18\x01'
    b' \x01(\r\x12!\n\x19initial_sleep_duration_ms\x18\x02'
    b' \x01(\r\x12\x1e\n\x16\x65xponential_multiplier\x18\x03'
    b' \x01(\x01\x12\x14\n\x0cjitter_range\x18\x04'
    b' \x01(\x01"-\n\x16ModelOutputRetryConfig\x12\x13\n\x0bmax_retries\x18\x01'
    b' \x01(\r"\x9d\x01\n\x0bRetryConfig\x12@\n\tapi_retry\x18\x01'
    b' \x01(\x0b\x32-.antigravity.localharness.ModelAPIRetryConfig\x12L\n\x12model_output_retry\x18\x02'
    b' \x01(\x0b\x32\x30.antigravity.localharness.ModelOutputRetryConfig"l\n\tWorkspace\x12M\n\x14\x66ilesystem_workspace\x18\x01'
    b' \x01(\x0b\x32-.antigravity.localharness.FilesystemWorkspaceH\x00\x42\x10\n\x0eworkspace_type"(\n\x13\x46ilesystemWorkspace\x12\x11\n\tdirectory\x18\x01'
    b' \x01(\t",\n\x12GeminiModelOptions\x12\x16\n\x0ethinking_level\x18\x01'
    b' \x01(\t"\xfd\x01\n\x11GeminiAPIEndpoint\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t\x12R\n\x0chttp_headers\x18\x02'
    b' \x03(\x0b\x32<.antigravity.localharness.GeminiAPIEndpoint.HttpHeadersEntry\x12\x0f\n\x07\x61pi_key\x18\x03'
    b' \x01(\t\x12=\n\x07options\x18\x04'
    b' \x01(\x0b\x32,.antigravity.localharness.GeminiModelOptions\x1a\x32\n\x10HttpHeadersEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"\x89\x02\n\x0eVertexEndpoint\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t\x12O\n\x0chttp_headers\x18\x02'
    b' \x03(\x0b\x32\x39.antigravity.localharness.VertexEndpoint.HttpHeadersEntry\x12\x0f\n\x07project\x18\x03'
    b' \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12=\n\x07options\x18\x05'
    b' \x01(\x0b\x32,.antigravity.localharness.GeminiModelOptions\x1a\x32\n\x10HttpHeadersEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"\xf4\x02\n\x0bModelConfig\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x32\n\x05types\x18\x02'
    b' \x03(\x0e\x32#.antigravity.localharness.ModelType\x12J\n\x13gemini_api_endpoint\x18\x03'
    b' \x01(\x0b\x32+.antigravity.localharness.GeminiAPIEndpointH\x00\x12\x43\n\x0fvertex_endpoint\x18\x04'
    b' \x01(\x0b\x32(.antigravity.localharness.VertexEndpointH\x00\x12\x41\n\x0egemma_endpoint\x18\x06'
    b" \x01(\x0b\x32'.antigravity.localharness.GemmaEndpointH\x00\x12\x43\n\x0f\x63ustom_endpoint\x18\x07"
    b' \x01(\x0b\x32(.antigravity.localharness.CustomEndpointH\x00\x42\n\n\x08\x65ndpoint"!\n\rGemmaEndpoint\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t";\n\x0e\x43ustomEndpoint\x12\x14\n\x0c\x62\x61\x63kend_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02'
    b' \x01(\t"\xac\x01\n\x12SystemInstructions\x12\x44\n\x06\x63ustom\x18\x01'
    b' \x01(\x0b\x32\x32.antigravity.localharness.CustomSystemInstructionsH\x00\x12H\n\x08\x61ppended\x18\x02'
    b' \x01(\x0b\x32\x34.antigravity.localharness.AppendedSystemInstructionsH\x00\x42\x06\n\x04type"\x9d\x03\n\x18\x43ustomSystemInstructions\x12\x45\n\x04part\x18\x01'
    b' \x03(\x0b\x32\x37.antigravity.localharness.CustomSystemInstructions.Part\x1a\x80\x01\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x12`\n\x08template\x18\x02'
    b' \x01(\x0b\x32L.antigravity.localharness.CustomSystemInstructions.SystemInstructionTemplateH\x00\x42\x06\n\x04part\x1a\xb6\x01\n\x19SystemInstructionTemplate\x12\x15\n\rtemplate_name\x18\x01'
    b' \x01(\t\x12^\n\x04\x61rgs\x18\x02'
    b' \x03(\x0b\x32P.antigravity.localharness.CustomSystemInstructions.SystemInstructionTemplate.Arg\x1a"\n\x03\x41rg\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t"\xb9\x01\n\x1a\x41ppendedSystemInstructions\x12\x17\n\x0f\x63ustom_identity\x18\x01'
    b' \x01(\t\x12W\n\x11\x61ppended_sections\x18\x02'
    b' \x03(\x0b\x32<.antigravity.localharness.AppendedSystemInstructions.Section\x1a)\n\x07Section\x12\r\n\x05title\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02'
    b' \x01(\t"\x91\x01\n\x04Tool\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x1e\n\x16parameters_json_schema\x18\x03'
    b' \x01(\t\x12\x1c\n\x14response_json_schema\x18\x04'
    b' \x01(\t\x12\x15\n\rdefer_loading\x18\x05'
    b' \x01(\x08*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02"\xe1\x07\n\x10HarnessSideTools\x12\x36\n\x04\x66ind\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.FindToolConfig\x12\x43\n\x0brun_command\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.RunCommandToolConfig\x12<\n\tsubagents\x18\x03'
    b' \x01(\x0b\x32).antigravity.localharness.SubagentsConfig\x12\x45\n\x0euser_questions\x18\x04'
    b' \x01(\x0b\x32-.antigravity.localharness.UserQuestionsConfig\x12?\n\tfile_edit\x18\x05'
    b' \x01(\x0b\x32,.antigravity.localharness.FileEditToolConfig\x12?\n\tview_file\x18\x06'
    b' \x01(\x0b\x32,.antigravity.localharness.ViewFileToolConfig\x12\x46\n\rwrite_to_file\x18\x07'
    b' \x01(\x0b\x32/.antigravity.localharness.WriteToFileToolConfig\x12\x43\n\x0bgrep_search\x18\x08'
    b' \x01(\x0b\x32..antigravity.localharness.GrepSearchToolConfig\x12=\n\x08list_dir\x18\t'
    b' \x01(\x0b\x32+.antigravity.localharness.ListDirToolConfig\x12@\n\x0bpermissions\x18\n'
    b' \x01(\x0b\x32+.antigravity.localharness.PermissionsConfig\x12I\n\x0egenerate_image\x18\x0b'
    b' \x01(\x0b\x32\x31.antigravity.localharness.GenerateImageToolConfig\x12\x41\n\nsearch_web\x18\x0c'
    b' \x01(\x0b\x32-.antigravity.localharness.SearchWebToolConfig\x12L\n\x10read_url_content\x18\x0e'
    b' \x01(\x0b\x32\x32.antigravity.localharness.ReadUrlContentToolConfig\x12\x46\n\x12tool_search_config\x18\x0f'
    b' \x01(\x0b\x32*.antigravity.localharness.ToolSearchConfig*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02J\x04\x08\r\x10\x0e"@\n\x0e\x46indToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04"\'\n\x14RunCommandToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08""\n\x0fSubagentsConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"&\n\x13UserQuestionsConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"%\n\x12\x46ileEditToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"%\n\x12ViewFileToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"(\n\x15WriteToFileToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"F\n\x14GrepSearchToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04"$\n\x11ListDirToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"0\n\x17GenerateImageToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08J\x04\x08\x02\x10\x03"&\n\x13SearchWebToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08"+\n\x18ReadUrlContentToolConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08".\n\x10ToolSearchConfig\x12\x0f\n\x07\x65nabled\x18\x01'
    b' \x01(\x08*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02"9\n\x11PermissionsConfig\x12$\n\x1c\x65nforce_workspace_validation\x18\x01'
    b' \x01(\x08"-\n\x0cOutputConfig\x12\x0c\n\x04port\x18\x01'
    b' \x01(\x05\x12\x0f\n\x07\x61pi_key\x18\x02'
    b' \x01(\t"\x9a\x04\n\x0bOutputEvent\x12\x0f\n\x07seq_num\x18\x01'
    b' \x01(\x03\x12\x18\n\x10timestamp_micros\x18\x02'
    b' \x01(\x03\x12;\n\x0bstep_update\x18\n'
    b' \x01(\x0b\x32$.antigravity.localharness.StepUpdateH\x00\x12R\n\x17trajectory_state_update\x18\x0b'
    b' \x01(\x0b\x32/.antigravity.localharness.TrajectoryStateUpdateH\x00\x12\x37\n\ttool_call\x18\x0c'
    b' \x01(\x0b\x32".antigravity.localharness.ToolCallH\x00\x12\x64\n'
    b' initialize_conversation_response\x18\r'
    b' \x01(\x0b\x32\x38.antigravity.localharness.InitializeConversationResponseH\x00\x12\x46\n\x11\x63\x61ll_hook_request\x18\x0e'
    b' \x01(\x0b\x32).antigravity.localharness.CallHookRequestH\x00\x12\x1e\n\x14session_end_response\x18\x0f'
    b' \x01(\x08H\x00\x12?\n\x0eusage_metadata\x18\x14'
    b' \x01(\x0b\x32\'.antigravity.localharness.UsageMetadataB\x07\n\x05\x65vent"k\n\x1eInitializeConversationResponse\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x35\n\x07history\x18\x02'
    b' \x03(\x0b\x32$.antigravity.localharness.StepUpdate"\xd2\x0e\n\nStepUpdate\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x03 \x01(\r\x12\x39\n\x05state\x18\x04'
    b' \x01(\x0e\x32*.antigravity.localharness.StepUpdate.State\x12;\n\x06source\x18\x05'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Source\x12;\n\x06target\x18\x06'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Target\x12\x15\n\rerror_message\x18\x07'
    b' \x01(\t\x12\x10\n\x08thinking\x18\x08'
    b' \x01(\t\x12\x12\n\ntext_delta\x18\t'
    b' \x01(\t\x12\x16\n\x0ethinking_delta\x18\n'
    b' \x01(\t\x12\x0c\n\x04text\x18\x14'
    b' \x01(\t\x12\x45\n\x0elist_directory\x18\x15'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionListDirectory\x12;\n\tfind_file\x18\x16'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionFindFile\x12I\n\x10search_directory\x18\x17'
    b' \x01(\x0b\x32/.antigravity.localharness.ActionSearchDirectory\x12;\n\tview_file\x18\x18'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionViewFile\x12?\n\x0b\x63reate_file\x18\x19'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCreateFile\x12;\n\tedit_file\x18\x1a'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionEditFile\x12?\n\x0brun_command\x18\x1b'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionRunCommand\x12>\n\ncompaction\x18\x1c'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCompaction\x12G\n\x0finvoke_subagent\x18\x1d'
    b' \x01(\x0b\x32..antigravity.localharness.ActionInvokeSubagent\x12\x45\n\x0egenerate_image\x18\x1e'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionGenerateImage\x12\x36\n\x06\x66inish\x18\x1f'
    b' \x01(\x0b\x32&.antigravity.localharness.ActionFinish\x12\x34\n\x05\x65rror\x18'
    b'  \x01(\x0b\x32%.antigravity.localharness.ActionError\x12\x39\n\x08mcp_tool\x18!'
    b' \x01(\x0b\x32\'.antigravity.localharness.ActionMcpTool\x12=\n\nsearch_web\x18"'
    b' \x01(\x0b\x32).antigravity.localharness.ActionSearchWeb\x12H\n\x10read_url_content\x18#'
    b' \x01(\x0b\x32..antigravity.localharness.ActionReadUrlContent\x12?\n\x0b\x63ustom_tool\x18$'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCustomTool\x12\x14\n\x0crequest_text\x18\x32'
    b' \x01(\t\x12T\n\x19tool_confirmation_request\x18\x33'
    b' \x01(\x0b\x32\x31.antigravity.localharness.ToolConfirmationRequest\x12I\n\x11questions_request\x18\x34'
    b' \x01(\x0b\x32..antigravity.localharness.UserQuestionsRequest"s\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATE_ACTIVE\x10\x01\x12\x0e\n\nSTATE_DONE\x10\x02\x12\x1a\n\x16STATE_WAITING_FOR_USER\x10\x03\x12\x0f\n\x0bSTATE_ERROR\x10\x04"\x04\x08\x05\x10\x05"V\n\x06Source\x12\x16\n\x12SOURCE_UNSPECIFIED\x10\x00\x12\x11\n\rSOURCE_SYSTEM\x10\x01\x12\x0f\n\x0bSOURCE_USER\x10\x02\x12\x10\n\x0cSOURCE_MODEL\x10\x03"[\n\x06Target\x12\x16\n\x12TARGET_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTARGET_USER\x10\x01\x12\x10\n\x0cTARGET_MODEL\x10\x02\x12\x16\n\x12TARGET_ENVIRONMENT\x10\x03"d\n\x13\x41\x63tionGenerateImage\x12\x0e\n\x06prompt\x18\x01'
    b' \x01(\t\x12\x13\n\x0bimage_paths\x18\x02'
    b' \x03(\t\x12\x12\n\nimage_name\x18\x03'
    b' \x01(\t\x12\x14\n\x0c\x61spect_ratio\x18\x04'
    b' \x01(\t"A\n\x0f\x41\x63tionSearchWeb\x12\r\n\x05query\x18\x01'
    b' \x01(\t\x12\x0e\n\x06\x64omain\x18\x02'
    b' \x01(\t\x12\x0f\n\x07summary\x18\x03'
    b' \x01(\t"Y\n\x14\x41\x63tionReadUrlContent\x12\x0b\n\x03url\x18\x01'
    b' \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03'
    b' \x01(\t\x12\x14\n\x0c\x63ontent_path\x18\x04'
    b' \x01(\t"%\n\x0c\x41\x63tionFinish\x12\x15\n\routput_string\x18\x01'
    b' \x01(\t"7\n\x0b\x41\x63tionError\x12\x15\n\rerror_message\x18\x01'
    b' \x01(\t\x12\x11\n\thttp_code\x18\x02'
    b' \x01(\r"\xc1\x01\n\x13\x41\x63tionListDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\x45\n\x07results\x18\x02'
    b' \x03(\x0b\x32\x34.antigravity.localharness.ActionListDirectory.Result\x1aK\n\x06Result\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x16\n\x0cis_directory\x18\x02'
    b' \x01(\x08H\x00\x12\x13\n\tfile_size\x18\x03'
    b' \x01(\x04H\x00\x42\x06\n\x04info"G\n\x0e\x41\x63tionFindFile\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03'
    b' \x01(\t"S\n\x15\x41\x63tionSearchDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02'
    b' \x01(\t\x12\x13\n\x0bnum_results\x18\x03'
    b' \x01(\x05"I\n\x0e\x41\x63tionViewFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x12\n\nstart_line\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x65nd_line\x18\x03'
    b' \x01(\r"7\n\x10\x41\x63tionCreateFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x10\n\x08\x63ontents\x18\x02'
    b' \x01(\t"\xba\x03\n\x0e\x41\x63tionEditFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x46\n\ndiff_block\x18\x02'
    b' \x03(\x0b\x32\x32.antigravity.localharness.ActionEditFile.DiffBlock\x1a\xd7\x01\n\x08\x44iffLine\x12\x0c\n\x04text\x18\x01'
    b' \x01(\t\x12L\n\x06\x61\x63tion\x18\x02'
    b' \x01(\x0e\x32<.antigravity.localharness.ActionEditFile.DiffLine.LineAction"o\n\nLineAction\x12\x1b\n\x17LINE_ACTION_UNSPECIFIED\x10\x00\x12\x16\n\x12LINE_ACTION_INSERT\x10\x01\x12\x16\n\x12LINE_ACTION_DELETE\x10\x02\x12\x14\n\x10LINE_ACTION_NONE\x10\x03\x1as\n\tDiffBlock\x12\x12\n\nstart_line\x18\x01'
    b' \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x02'
    b' \x01(\x05\x12@\n\x05lines\x18\x03'
    b' \x03(\x0b\x32\x31.antigravity.localharness.ActionEditFile.DiffLine"i\n\x10\x41\x63tionRunCommand\x12\x14\n\x0c\x63ommand_line\x18\x01'
    b' \x01(\t\x12\x13\n\x0bworking_dir\x18\x02'
    b' \x01(\t\x12\x11\n\texit_code\x18\x04'
    b' \x01(\x05\x12\x17\n\x0f\x63ombined_output\x18\x05'
    b' \x01(\t"\x12\n\x10\x41\x63tionCompaction"\x16\n\x14\x41\x63tionInvokeSubagent"\x19\n\x17ToolConfirmationRequest"Q\n\x14UserQuestionsRequest\x12\x39\n\tquestions\x18\x01'
    b' \x03(\x0b\x32&.antigravity.localharness.UserQuestion"d\n\x0cUserQuestion\x12\x43\n\x0fmultiple_choice\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.MultipleChoiceH\x00\x42\x0f\n\rquestion_type"L\n\x0eMultipleChoice\x12\x10\n\x08question\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63hoices\x18\x02'
    b' \x03(\t\x12\x17\n\x0fis_multi_select\x18\x03'
    b' \x01(\x08"\xe4\x03\n\nInputEvent\x12\x14\n\nuser_input\x18\x01'
    b' \x01(\tH\x00\x12\x41\n\x12\x63omplex_user_input\x18\x07'
    b' \x01(\x0b\x32#.antigravity.localharness.UserInputH\x00\x12G\n\x11tool_confirmation\x18\x02'
    b' \x01(\x0b\x32*.antigravity.localharness.ToolConfirmationH\x00\x12?\n\rtool_response\x18\x03'
    b' \x01(\x0b\x32&.antigravity.localharness.ToolResponseH\x00\x12L\n\x11question_response\x18\x04'
    b' \x01(\x0b\x32/.antigravity.localharness.UserQuestionsResponseH\x00\x12\x16\n\x0chalt_request\x18\x05'
    b' \x01(\x08H\x00\x12\x1b\n\x11\x61utomated_trigger\x18\x06'
    b' \x01(\tH\x00\x12H\n\x12\x63\x61ll_hook_response\x18\x08'
    b' \x01(\x0b\x32*.antigravity.localharness.CallHookResponseH\x00\x12\x1d\n\x13session_end_request\x18\t'
    b' \x01(\x08H\x00\x42\x07\n\x05\x65vent"\xc9\x02\n\tUserInput\x12\x37\n\x05parts\x18\x01'
    b' \x03(\x0b\x32(.antigravity.localharness.UserInput.Part\x1a=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c\x1a\x1c\n\x0cSlashCommand\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x1a\xa5\x01\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x12:\n\x05media\x18\x02'
    b' \x01(\x0b\x32).antigravity.localharness.UserInput.MediaH\x00\x12I\n\rslash_command\x18\x03'
    b' \x01(\x0b\x32\x30.antigravity.localharness.UserInput.SlashCommandH\x00\x42\x06\n\x04part"O\n\x10ToolConfirmation\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03'
    b' \x01(\x08"\xf8\x01\n\x15TrajectoryStateUpdate\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x44\n\x05state\x18\x03'
    b' \x01(\x0e\x32\x35.antigravity.localharness.TrajectoryStateUpdate.State\x12\r\n\x05\x65rror\x18\x04'
    b' \x01(\t"s\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n\rSTATE_RUNNING\x10\x01\x12\x0e\n\nSTATE_IDLE\x10\x02\x12\x13\n\x0fSTATE_CANCELLED\x10\x03\x12\x1b\n\x17STATE_WAITING_FOR_TASKS\x10\x04"9\n\x06Struct\x12/\n\x06\x66ields\x18\x01'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Field"E\n\x05\x46ield\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12.\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x1f.antigravity.localharness.Value"\xb7\x02\n\x05Value\x12\x39\n\nnull_value\x18\x01'
    b' \x01(\x0e\x32#.antigravity.localharness.NullValueH\x00\x12\x16\n\x0cnumber_value\x18\x02'
    b' \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03'
    b' \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04'
    b' \x01(\x08H\x00\x12\x38\n\x0cstruct_value\x18\x05 \x01(\x0b\x32'
    b' .antigravity.localharness.StructH\x00\x12\x39\n\nlist_value\x18\x06'
    b' \x01(\x0b\x32#.antigravity.localharness.ListValueH\x00\x12\x30\n\x05media\x18\x07'
    b' \x01(\x0b\x32\x1f.antigravity.localharness.MediaH\x00\x42\x06\n\x04kind"<\n\tListValue\x12/\n\x06values\x18\x01'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Value"\x84\x01\n\x08ToolCall\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04name\x18\x02'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03'
    b' \x01(\t\x12\x33\n\targuments\x18\x04 \x01(\x0b\x32'
    b' .antigravity.localharness.Struct*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02"\xcc\x01\n\x0cToolResponse\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x15\n\rresponse_json\x18\x02'
    b' \x01(\t\x12;\n\x12supplemental_media\x18\x03'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Media\x12\x32\n\x08response\x18\x04'
    b' \x01(\x0b\x32'
    b' .antigravity.localharness.Struct\x12\x15\n\rerror_message\x18\x05'
    b' \x01(\t*\x06\x08\xe8\x07\x10\xd0\x0f*\t\x08\xd0\x0f\x10\x80\x80\x80\x80\x02"\x8c\x02\n\x15UserQuestionsResponse\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x13\n\tcancelled\x18\x03'
    b' \x01(\x08H\x00\x12U\n\x08response\x18\x04'
    b' \x01(\x0b\x32\x41.antigravity.localharness.UserQuestionsResponse.QuestionsResponseH\x00\x1aR\n\x11QuestionsResponse\x12=\n\x07\x61nswers\x18\x01'
    b' \x03(\x0b\x32,.antigravity.localharness.UserQuestionAnswerB\x08\n\x06result"\x86\x01\n\x12UserQuestionAnswer\x12\x14\n\nunanswered\x18\x01'
    b' \x01(\x08H\x00\x12P\n\x16multiple_choice_answer\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.MultipleChoiceAnswerH\x00\x42\x08\n\x06\x61nswer"R\n\x14MultipleChoiceAnswer\x12\x1f\n\x17selected_choice_indices\x18\x01'
    b' \x03(\x05\x12\x19\n\x11\x66reeform_response\x18\x02'
    b' \x01(\t"=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c"\xa8\x01\n\rUsageMetadata\x12\x1a\n\x12prompt_token_count\x18\x01'
    b' \x01(\x04\x12"\n\x1a\x63\x61\x63hed_content_token_count\x18\x05'
    b' \x01(\x04\x12\x1e\n\x16\x63\x61ndidates_token_count\x18\x02'
    b' \x01(\x04\x12\x1c\n\x14thoughts_token_count\x18\x04'
    b' \x01(\x04\x12\x19\n\x11total_token_count\x18\x03'
    b' \x01(\x04"\xa9\x03\n\x0fMcpServerConfig\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12<\n\x05stdio\x18\x02'
    b' \x01(\x0b\x32+.antigravity.localharness.McpStdioTransportH\x00\x12:\n\x04http\x18\x03'
    b' \x01(\x0b\x32*.antigravity.localharness.McpHttpTransportH\x00\x12\x15\n\renabled_tools\x18\x04'
    b' \x03(\t\x12\x16\n\x0e\x64isabled_tools\x18\x05'
    b' \x03(\t\x12V\n\x12\x61uth_provider_type\x18\x06'
    b' \x01(\x0e\x32:.antigravity.localharness.McpServerConfig.AuthProviderType\x12\x17\n\x0ftimeout_seconds\x18\x07'
    b' \x01(\x05"a\n\x10\x41uthProviderType\x12"\n\x1e\x41UTH_PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12)\n%AUTH_PROVIDER_TYPE_GOOGLE_CREDENTIALS\x10\x01\x42\x0b\n\ttransport"\xa1\x01\n\x11McpStdioTransport\x12\x0f\n\x07\x63ommand\x18\x01'
    b' \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x41\n\x03\x65nv\x18\x03'
    b' \x03(\x0b\x32\x34.antigravity.localharness.McpStdioTransport.EnvEntry\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"\x99\x01\n\x10McpHttpTransport\x12\x0b\n\x03url\x18\x01'
    b' \x01(\t\x12H\n\x07headers\x18\x02'
    b' \x03(\x0b\x32\x37.antigravity.localharness.McpHttpTransport.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"O\n\rActionMcpTool\x12\x13\n\x0bserver_name\x18\x01'
    b' \x01(\t\x12\x11\n\ttool_name\x18\x02'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03'
    b' \x01(\t"\x88\x01\n\x10\x41\x63tionCustomTool\x12\x35\n\ttool_call\x18\x01'
    b' \x01(\x0b\x32".antigravity.localharness.ToolCall\x12=\n\rtool_response\x18\x02'
    b' \x01(\x0b\x32&.antigravity.localharness.ToolResponse"\xbf\x03\n\x0f\x43\x61llHookRequest\x12\x12\n\nrequest_id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x35\n\x04type\x18\x07'
    b" \x01(\x0e\x32'.antigravity.localharness.LifecycleHook\x12>\n\rpre_turn_args\x18\x03"
    b' \x01(\x0b\x32%.antigravity.localharness.PreTurnArgsH\x00\x12@\n\x0epost_turn_args\x18\x04'
    b' \x01(\x0b\x32&.antigravity.localharness.PostTurnArgsH\x00\x12>\n\rpre_tool_args\x18\x05'
    b' \x01(\x0b\x32%.antigravity.localharness.PreToolArgsH\x00\x12@\n\x0epost_tool_args\x18\x06'
    b' \x01(\x0b\x32&.antigravity.localharness.PostToolArgsH\x00\x12G\n\x12on_tool_error_args\x18\x08'
    b' \x01(\x0b\x32).antigravity.localharness.OnToolErrorArgsH\x00\x42\x06\n\x04\x61rgs"\xdd\x02\n\x10\x43\x61llHookResponse\x12\x12\n\nrequest_id\x18\x01'
    b' \x01(\t\x12\x42\n\x0fpre_turn_result\x18\x02'
    b" \x01(\x0b\x32'.antigravity.localharness.PreTurnResultH\x00\x12\x42\n\x0fpre_tool_result\x18\x03"
    b" \x01(\x0b\x32'.antigravity.localharness.PreToolResultH\x00\x12=\n\x0c\x65mpty_result\x18\x04"
    b' \x01(\x0b\x32%.antigravity.localharness.EmptyResultH\x00\x12\x17\n\rerror_message\x18\x05'
    b' \x01(\tH\x00\x12K\n\x14on_tool_error_result\x18\x06'
    b' \x01(\x0b\x32+.antigravity.localharness.OnToolErrorResultH\x00\x42\x08\n\x06result"M\n\x0bPreToolArgs\x12\x11\n\ttool_name\x18\x01'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02'
    b' \x01(\t\x12\x13\n\x0bserver_name\x18\x03'
    b' \x01(\t"h\n\x0cPostToolArgs\x12\x11\n\ttool_name\x18\x01'
    b' \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03'
    b' \x01(\t\x12\x13\n\x0bserver_name\x18\x05'
    b' \x01(\tJ\x04\x08\x04\x10\x05R\x0bstep_update"c\n\x0fOnToolErrorArgs\x12\x11\n\ttool_name\x18\x01'
    b' \x01(\t\x12\x15\n\rerror_message\x18\x02'
    b' \x01(\t\x12\x13\n\x0bserver_name\x18\x04'
    b' \x01(\tJ\x04\x08\x03\x10\x04R\x0bstep_update"F\n\x0bPreTurnArgs\x12\x37\n\nuser_input\x18\x01'
    b' \x01(\x0b\x32#.antigravity.localharness.UserInput"%\n\x0cPostTurnArgs\x12\x15\n\rresponse_text\x18\x01'
    b' \x01(\t"\r\n\x0b\x45mptyResult"1\n\x11OnToolErrorResult\x12\x1c\n\x14\x63ustom_error_message\x18\x01'
    b' \x01(\t"\xbf\x01\n\rPreToolResult\x12\x42\n\x08\x64\x65\x63ision\x18\x01'
    b' \x01(\x0e\x32\x30.antigravity.localharness.PreToolResult.Decision\x12\x0e\n\x06reason\x18\x02'
    b' \x01(\t\x12\x1f\n\x17modified_arguments_json\x18\x03'
    b' \x01(\t"9\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\x08\n\x04\x44\x45NY\x10\x02"\x9e\x01\n\rPreTurnResult\x12\x42\n\x08\x64\x65\x63ision\x18\x01'
    b' \x01(\x0e\x32\x30.antigravity.localharness.PreTurnResult.Decision\x12\x0e\n\x06reason\x18\x02'
    b' \x01(\t"9\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\x08\n\x04\x44\x45NY\x10\x02"\xf2\x01\n\x0b\x43ustomAgent\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12I\n\x13system_instructions\x18\x03'
    b' \x01(\x0b\x32,.antigravity.localharness.SystemInstructions\x12\x46\n\x12harness_side_tools\x18\x04'
    b' \x01(\x0b\x32*.antigravity.localharness.HarnessSideTools\x12-\n\x05tools\x18\x05'
    b' \x03(\x0b\x32\x1e.antigravity.localharness.Tool"\xaa\x02\n\x14ToolOutputTruncation\x12S\n\x08truncate\x18\x01'
    b' \x01(\x0b\x32?.antigravity.localharness.ToolOutputTruncation.TruncateStrategyH\x00\x12M\n\x05\x65rror\x18\x02'
    b' \x01(\x0b\x32<.antigravity.localharness.ToolOutputTruncation.ErrorStrategyH\x00\x1a&\n\x10TruncateStrategy\x12\x12\n\nmax_tokens\x18\x01'
    b' \x01(\x05\x1a:\n\rErrorStrategy\x12\x12\n\nmax_tokens\x18\x01'
    b' \x01(\x05\x12\x15\n\rerror_message\x18\x02'
    b' \x01(\tB\n\n\x08strategy*\x8f\x02\n\rLifecycleHook\x12\x1e\n\x1aLIFECYCLE_HOOK_UNSPECIFIED\x10\x00\x12#\n\x1fLIFECYCLE_HOOK_ON_SESSION_START\x10\x01\x12!\n\x1dLIFECYCLE_HOOK_ON_SESSION_END\x10\x02\x12\x1b\n\x17LIFECYCLE_HOOK_PRE_TURN\x10\x03\x12\x1c\n\x18LIFECYCLE_HOOK_POST_TURN\x10\x04\x12\x1b\n\x17LIFECYCLE_HOOK_PRE_TOOL\x10\x05\x12\x1c\n\x18LIFECYCLE_HOOK_POST_TOOL\x10\x06\x12'
    b' \n\x1cLIFECYCLE_HOOK_ON_TOOL_ERROR\x10\x07*R\n\tModelType\x12\x1a\n\x16MODEL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fMODEL_TYPE_TEXT\x10\x01\x12\x14\n\x10MODEL_TYPE_IMAGE\x10\x02*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x62\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'localharness_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTCONFIG_ENVENTRY']._loaded_options = None
  _globals['_INPUTCONFIG_ENVENTRY']._serialized_options = b'8\001'
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._loaded_options = None
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._loaded_options = None
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._loaded_options = None
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._serialized_options = b'8\001'
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._loaded_options = None
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_LIFECYCLEHOOK']._serialized_start = 15842
  _globals['_LIFECYCLEHOOK']._serialized_end = 16113
  _globals['_MODELTYPE']._serialized_start = 16115
  _globals['_MODELTYPE']._serialized_end = 16197
  _globals['_NULLVALUE']._serialized_start = 16199
  _globals['_NULLVALUE']._serialized_end = 16226
  _globals['_INPUTCONFIG']._serialized_start = 49
  _globals['_INPUTCONFIG']._serialized_end = 300
  _globals['_INPUTCONFIG_ENVENTRY']._serialized_start = 258
  _globals['_INPUTCONFIG_ENVENTRY']._serialized_end = 300
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_start = 302
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_end = 388
  _globals['_CLIENTINFO']._serialized_start = 390
  _globals['_CLIENTINFO']._serialized_end = 495
  _globals['_HARNESSCONFIG']._serialized_start = 498
  _globals['_HARNESSCONFIG']._serialized_end = 1566
  _globals['_HARNESSCONFIG_SESSIONCONTINUATIONMODE']._serialized_start = 1410
  _globals['_HARNESSCONFIG_SESSIONCONTINUATIONMODE']._serialized_end = 1529
  _globals['_MODELAPIRETRYCONFIG']._serialized_start = 1569
  _globals['_MODELAPIRETRYCONFIG']._serialized_end = 1700
  _globals['_MODELOUTPUTRETRYCONFIG']._serialized_start = 1702
  _globals['_MODELOUTPUTRETRYCONFIG']._serialized_end = 1747
  _globals['_RETRYCONFIG']._serialized_start = 1750
  _globals['_RETRYCONFIG']._serialized_end = 1907
  _globals['_WORKSPACE']._serialized_start = 1909
  _globals['_WORKSPACE']._serialized_end = 2017
  _globals['_FILESYSTEMWORKSPACE']._serialized_start = 2019
  _globals['_FILESYSTEMWORKSPACE']._serialized_end = 2059
  _globals['_GEMINIMODELOPTIONS']._serialized_start = 2061
  _globals['_GEMINIMODELOPTIONS']._serialized_end = 2105
  _globals['_GEMINIAPIENDPOINT']._serialized_start = 2108
  _globals['_GEMINIAPIENDPOINT']._serialized_end = 2361
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._serialized_start = 2311
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._serialized_end = 2361
  _globals['_VERTEXENDPOINT']._serialized_start = 2364
  _globals['_VERTEXENDPOINT']._serialized_end = 2629
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._serialized_start = 2311
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._serialized_end = 2361
  _globals['_MODELCONFIG']._serialized_start = 2632
  _globals['_MODELCONFIG']._serialized_end = 3004
  _globals['_GEMMAENDPOINT']._serialized_start = 3006
  _globals['_GEMMAENDPOINT']._serialized_end = 3039
  _globals['_CUSTOMENDPOINT']._serialized_start = 3041
  _globals['_CUSTOMENDPOINT']._serialized_end = 3100
  _globals['_SYSTEMINSTRUCTIONS']._serialized_start = 3103
  _globals['_SYSTEMINSTRUCTIONS']._serialized_end = 3275
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_start = 3278
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_end = 3691
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_start = 3378
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_end = 3506
  _globals[
      '_CUSTOMSYSTEMINSTRUCTIONS_SYSTEMINSTRUCTIONTEMPLATE'
  ]._serialized_start = 3509
  _globals[
      '_CUSTOMSYSTEMINSTRUCTIONS_SYSTEMINSTRUCTIONTEMPLATE'
  ]._serialized_end = 3691
  _globals[
      '_CUSTOMSYSTEMINSTRUCTIONS_SYSTEMINSTRUCTIONTEMPLATE_ARG'
  ]._serialized_start = 3657
  _globals[
      '_CUSTOMSYSTEMINSTRUCTIONS_SYSTEMINSTRUCTIONTEMPLATE_ARG'
  ]._serialized_end = 3691
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_start = 3694
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_end = 3879
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_start = 3838
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_end = 3879
  _globals['_TOOL']._serialized_start = 3882
  _globals['_TOOL']._serialized_end = 4027
  _globals['_HARNESSSIDETOOLS']._serialized_start = 4030
  _globals['_HARNESSSIDETOOLS']._serialized_end = 5023
  _globals['_FINDTOOLCONFIG']._serialized_start = 5025
  _globals['_FINDTOOLCONFIG']._serialized_end = 5089
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_start = 5091
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_end = 5130
  _globals['_SUBAGENTSCONFIG']._serialized_start = 5132
  _globals['_SUBAGENTSCONFIG']._serialized_end = 5166
  _globals['_USERQUESTIONSCONFIG']._serialized_start = 5168
  _globals['_USERQUESTIONSCONFIG']._serialized_end = 5206
  _globals['_FILEEDITTOOLCONFIG']._serialized_start = 5208
  _globals['_FILEEDITTOOLCONFIG']._serialized_end = 5245
  _globals['_VIEWFILETOOLCONFIG']._serialized_start = 5247
  _globals['_VIEWFILETOOLCONFIG']._serialized_end = 5284
  _globals['_WRITETOFILETOOLCONFIG']._serialized_start = 5286
  _globals['_WRITETOFILETOOLCONFIG']._serialized_end = 5326
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_start = 5328
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_end = 5398
  _globals['_LISTDIRTOOLCONFIG']._serialized_start = 5400
  _globals['_LISTDIRTOOLCONFIG']._serialized_end = 5436
  _globals['_GENERATEIMAGETOOLCONFIG']._serialized_start = 5438
  _globals['_GENERATEIMAGETOOLCONFIG']._serialized_end = 5486
  _globals['_SEARCHWEBTOOLCONFIG']._serialized_start = 5488
  _globals['_SEARCHWEBTOOLCONFIG']._serialized_end = 5526
  _globals['_READURLCONTENTTOOLCONFIG']._serialized_start = 5528
  _globals['_READURLCONTENTTOOLCONFIG']._serialized_end = 5571
  _globals['_TOOLSEARCHCONFIG']._serialized_start = 5573
  _globals['_TOOLSEARCHCONFIG']._serialized_end = 5619
  _globals['_PERMISSIONSCONFIG']._serialized_start = 5621
  _globals['_PERMISSIONSCONFIG']._serialized_end = 5678
  _globals['_OUTPUTCONFIG']._serialized_start = 5680
  _globals['_OUTPUTCONFIG']._serialized_end = 5725
  _globals['_OUTPUTEVENT']._serialized_start = 5728
  _globals['_OUTPUTEVENT']._serialized_end = 6266
  _globals['_INITIALIZECONVERSATIONRESPONSE']._serialized_start = 6268
  _globals['_INITIALIZECONVERSATIONRESPONSE']._serialized_end = 6375
  _globals['_STEPUPDATE']._serialized_start = 6378
  _globals['_STEPUPDATE']._serialized_end = 8252
  _globals['_STEPUPDATE_STATE']._serialized_start = 7956
  _globals['_STEPUPDATE_STATE']._serialized_end = 8071
  _globals['_STEPUPDATE_SOURCE']._serialized_start = 8073
  _globals['_STEPUPDATE_SOURCE']._serialized_end = 8159
  _globals['_STEPUPDATE_TARGET']._serialized_start = 8161
  _globals['_STEPUPDATE_TARGET']._serialized_end = 8252
  _globals['_ACTIONGENERATEIMAGE']._serialized_start = 8254
  _globals['_ACTIONGENERATEIMAGE']._serialized_end = 8354
  _globals['_ACTIONSEARCHWEB']._serialized_start = 8356
  _globals['_ACTIONSEARCHWEB']._serialized_end = 8421
  _globals['_ACTIONREADURLCONTENT']._serialized_start = 8423
  _globals['_ACTIONREADURLCONTENT']._serialized_end = 8512
  _globals['_ACTIONFINISH']._serialized_start = 8514
  _globals['_ACTIONFINISH']._serialized_end = 8551
  _globals['_ACTIONERROR']._serialized_start = 8553
  _globals['_ACTIONERROR']._serialized_end = 8608
  _globals['_ACTIONLISTDIRECTORY']._serialized_start = 8611
  _globals['_ACTIONLISTDIRECTORY']._serialized_end = 8804
  _globals['_ACTIONLISTDIRECTORY_RESULT']._serialized_start = 8729
  _globals['_ACTIONLISTDIRECTORY_RESULT']._serialized_end = 8804
  _globals['_ACTIONFINDFILE']._serialized_start = 8806
  _globals['_ACTIONFINDFILE']._serialized_end = 8877
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_start = 8879
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_end = 8962
  _globals['_ACTIONVIEWFILE']._serialized_start = 8964
  _globals['_ACTIONVIEWFILE']._serialized_end = 9037
  _globals['_ACTIONCREATEFILE']._serialized_start = 9039
  _globals['_ACTIONCREATEFILE']._serialized_end = 9094
  _globals['_ACTIONEDITFILE']._serialized_start = 9097
  _globals['_ACTIONEDITFILE']._serialized_end = 9539
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_start = 9207
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_end = 9422
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_start = 9311
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_end = 9422
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_start = 9424
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_end = 9539
  _globals['_ACTIONRUNCOMMAND']._serialized_start = 9541
  _globals['_ACTIONRUNCOMMAND']._serialized_end = 9646
  _globals['_ACTIONCOMPACTION']._serialized_start = 9648
  _globals['_ACTIONCOMPACTION']._serialized_end = 9666
  _globals['_ACTIONINVOKESUBAGENT']._serialized_start = 9668
  _globals['_ACTIONINVOKESUBAGENT']._serialized_end = 9690
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_start = 9692
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_end = 9717
  _globals['_USERQUESTIONSREQUEST']._serialized_start = 9719
  _globals['_USERQUESTIONSREQUEST']._serialized_end = 9800
  _globals['_USERQUESTION']._serialized_start = 9802
  _globals['_USERQUESTION']._serialized_end = 9902
  _globals['_MULTIPLECHOICE']._serialized_start = 9904
  _globals['_MULTIPLECHOICE']._serialized_end = 9980
  _globals['_INPUTEVENT']._serialized_start = 9983
  _globals['_INPUTEVENT']._serialized_end = 10467
  _globals['_USERINPUT']._serialized_start = 10470
  _globals['_USERINPUT']._serialized_end = 10799
  _globals['_USERINPUT_MEDIA']._serialized_start = 10540
  _globals['_USERINPUT_MEDIA']._serialized_end = 10601
  _globals['_USERINPUT_SLASHCOMMAND']._serialized_start = 10603
  _globals['_USERINPUT_SLASHCOMMAND']._serialized_end = 10631
  _globals['_USERINPUT_PART']._serialized_start = 10634
  _globals['_USERINPUT_PART']._serialized_end = 10799
  _globals['_TOOLCONFIRMATION']._serialized_start = 10801
  _globals['_TOOLCONFIRMATION']._serialized_end = 10880
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_start = 10883
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_end = 11131
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_start = 11016
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_end = 11131
  _globals['_STRUCT']._serialized_start = 11133
  _globals['_STRUCT']._serialized_end = 11190
  _globals['_FIELD']._serialized_start = 11192
  _globals['_FIELD']._serialized_end = 11261
  _globals['_VALUE']._serialized_start = 11264
  _globals['_VALUE']._serialized_end = 11575
  _globals['_LISTVALUE']._serialized_start = 11577
  _globals['_LISTVALUE']._serialized_end = 11637
  _globals['_TOOLCALL']._serialized_start = 11640
  _globals['_TOOLCALL']._serialized_end = 11772
  _globals['_TOOLRESPONSE']._serialized_start = 11775
  _globals['_TOOLRESPONSE']._serialized_end = 11979
  _globals['_USERQUESTIONSRESPONSE']._serialized_start = 11982
  _globals['_USERQUESTIONSRESPONSE']._serialized_end = 12250
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_start = 12158
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_end = 12240
  _globals['_USERQUESTIONANSWER']._serialized_start = 12253
  _globals['_USERQUESTIONANSWER']._serialized_end = 12387
  _globals['_MULTIPLECHOICEANSWER']._serialized_start = 12389
  _globals['_MULTIPLECHOICEANSWER']._serialized_end = 12471
  _globals['_MEDIA']._serialized_start = 10540
  _globals['_MEDIA']._serialized_end = 10601
  _globals['_USAGEMETADATA']._serialized_start = 12537
  _globals['_USAGEMETADATA']._serialized_end = 12705
  _globals['_MCPSERVERCONFIG']._serialized_start = 12708
  _globals['_MCPSERVERCONFIG']._serialized_end = 13133
  _globals['_MCPSERVERCONFIG_AUTHPROVIDERTYPE']._serialized_start = 13023
  _globals['_MCPSERVERCONFIG_AUTHPROVIDERTYPE']._serialized_end = 13120
  _globals['_MCPSTDIOTRANSPORT']._serialized_start = 13136
  _globals['_MCPSTDIOTRANSPORT']._serialized_end = 13297
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._serialized_start = 258
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._serialized_end = 300
  _globals['_MCPHTTPTRANSPORT']._serialized_start = 13300
  _globals['_MCPHTTPTRANSPORT']._serialized_end = 13453
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._serialized_start = 13407
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._serialized_end = 13453
  _globals['_ACTIONMCPTOOL']._serialized_start = 13455
  _globals['_ACTIONMCPTOOL']._serialized_end = 13534
  _globals['_ACTIONCUSTOMTOOL']._serialized_start = 13537
  _globals['_ACTIONCUSTOMTOOL']._serialized_end = 13673
  _globals['_CALLHOOKREQUEST']._serialized_start = 13676
  _globals['_CALLHOOKREQUEST']._serialized_end = 14123
  _globals['_CALLHOOKRESPONSE']._serialized_start = 14126
  _globals['_CALLHOOKRESPONSE']._serialized_end = 14475
  _globals['_PRETOOLARGS']._serialized_start = 14477
  _globals['_PRETOOLARGS']._serialized_end = 14554
  _globals['_POSTTOOLARGS']._serialized_start = 14556
  _globals['_POSTTOOLARGS']._serialized_end = 14660
  _globals['_ONTOOLERRORARGS']._serialized_start = 14662
  _globals['_ONTOOLERRORARGS']._serialized_end = 14761
  _globals['_PRETURNARGS']._serialized_start = 14763
  _globals['_PRETURNARGS']._serialized_end = 14833
  _globals['_POSTTURNARGS']._serialized_start = 14835
  _globals['_POSTTURNARGS']._serialized_end = 14872
  _globals['_EMPTYRESULT']._serialized_start = 14874
  _globals['_EMPTYRESULT']._serialized_end = 14887
  _globals['_ONTOOLERRORRESULT']._serialized_start = 14889
  _globals['_ONTOOLERRORRESULT']._serialized_end = 14938
  _globals['_PRETOOLRESULT']._serialized_start = 14941
  _globals['_PRETOOLRESULT']._serialized_end = 15132
  _globals['_PRETOOLRESULT_DECISION']._serialized_start = 15075
  _globals['_PRETOOLRESULT_DECISION']._serialized_end = 15132
  _globals['_PRETURNRESULT']._serialized_start = 15135
  _globals['_PRETURNRESULT']._serialized_end = 15293
  _globals['_PRETURNRESULT_DECISION']._serialized_start = 15075
  _globals['_PRETURNRESULT_DECISION']._serialized_end = 15132
  _globals['_CUSTOMAGENT']._serialized_start = 15296
  _globals['_CUSTOMAGENT']._serialized_end = 15538
  _globals['_TOOLOUTPUTTRUNCATION']._serialized_start = 15541
  _globals['_TOOLOUTPUTTRUNCATION']._serialized_end = 15839
  _globals['_TOOLOUTPUTTRUNCATION_TRUNCATESTRATEGY']._serialized_start = 15729
  _globals['_TOOLOUTPUTTRUNCATION_TRUNCATESTRATEGY']._serialized_end = 15767
  _globals['_TOOLOUTPUTTRUNCATION_ERRORSTRATEGY']._serialized_start = 15769
  _globals['_TOOLOUTPUTTRUNCATION_ERRORSTRATEGY']._serialized_end = 15827
# @@protoc_insertion_point(module_scope)
