# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pytype: skip-file
# pylint: disable=protected-access
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: localharness.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12localharness.proto\x12\x18\x61ntigravity.localharness"\x92\x01\n\x0bInputConfig\x12\x19\n\x11storage_directory\x18\x01'
    b' \x01(\t\x12\x0c\n\x04port\x18\x02'
    b' \x01(\r\x12\x1f\n\x0c\x62ind_address\x18\x03'
    b' \x01(\t:\tlocalhost\x12\x39\n\x0b\x63lient_info\x18\x04'
    b' \x01(\x0b\x32$.antigravity.localharness.ClientInfo"V\n\x1bInitializeConversationEvent\x12\x37\n\x06\x63onfig\x18\x01'
    b' \x01(\x0b\x32\'.antigravity.localharness.HarnessConfig"I\n\nClientInfo\x12\x10\n\x08language\x18\x01'
    b' \x01(\t\x12\x0f\n\x07version\x18\x02'
    b' \x01(\t\x12\x18\n\x10language_version\x18\x03'
    b' \x01(\t"\xee\x04\n\rHarnessConfig\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12I\n\x13system_instructions\x18\x04'
    b' \x01(\x0b\x32,.antigravity.localharness.SystemInstructions\x12-\n\x05tools\x18\x05'
    b' \x03(\x0b\x32\x1e.antigravity.localharness.Tool\x12\x46\n\x12harness_side_tools\x18\x06'
    b' \x01(\x0b\x32*.antigravity.localharness.HarnessSideTools\x12\x1c\n\x14\x63ompaction_threshold\x18\x07'
    b' \x01(\r\x12\x37\n\nworkspaces\x18\x08'
    b' \x03(\x0b\x32#.antigravity.localharness.Workspace\x12\x14\n\x0cskills_paths\x18\t'
    b' \x03(\t\x12\x1f\n\x17\x66inish_tool_schema_json\x18\n'
    b' \x01(\t\x12\x1a\n\x12initial_trajectory\x18\x0b'
    b' \x01(\x0c\x12\x14\n\x0c\x61pp_data_dir\x18\x0c'
    b' \x01(\t\x12>\n\x0bmcp_servers\x18\x0e'
    b' \x03(\x0b\x32).antigravity.localharness.McpServerConfig\x12\x35\n\x06models\x18\x0f'
    b' \x03(\x0b\x32%.antigravity.localharness.ModelConfig\x12>\n\renabled_hooks\x18\x10'
    b' \x03(\x0e\x32\'.antigravity.localharness.LifecycleHookJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\r\x10\x0e"l\n\tWorkspace\x12M\n\x14\x66ilesystem_workspace\x18\x01'
    b' \x01(\x0b\x32-.antigravity.localharness.FilesystemWorkspaceH\x00\x42\x10\n\x0eworkspace_type"(\n\x13\x46ilesystemWorkspace\x12\x11\n\tdirectory\x18\x01'
    b' \x01(\t",\n\x12GeminiModelOptions\x12\x16\n\x0ethinking_level\x18\x01'
    b' \x01(\t"\xfd\x01\n\x11GeminiAPIEndpoint\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t\x12R\n\x0chttp_headers\x18\x02'
    b' \x03(\x0b\x32<.antigravity.localharness.GeminiAPIEndpoint.HttpHeadersEntry\x12\x0f\n\x07\x61pi_key\x18\x03'
    b' \x01(\t\x12=\n\x07options\x18\x04'
    b' \x01(\x0b\x32,.antigravity.localharness.GeminiModelOptions\x1a\x32\n\x10HttpHeadersEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"\x89\x02\n\x0eVertexEndpoint\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t\x12O\n\x0chttp_headers\x18\x02'
    b' \x03(\x0b\x32\x39.antigravity.localharness.VertexEndpoint.HttpHeadersEntry\x12\x0f\n\x07project\x18\x03'
    b' \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12=\n\x07options\x18\x05'
    b' \x01(\x0b\x32,.antigravity.localharness.GeminiModelOptions\x1a\x32\n\x10HttpHeadersEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"\xf4\x02\n\x0bModelConfig\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x32\n\x05types\x18\x02'
    b' \x03(\x0e\x32#.antigravity.localharness.ModelType\x12J\n\x13gemini_api_endpoint\x18\x03'
    b' \x01(\x0b\x32+.antigravity.localharness.GeminiAPIEndpointH\x00\x12\x43\n\x0fvertex_endpoint\x18\x04'
    b' \x01(\x0b\x32(.antigravity.localharness.VertexEndpointH\x00\x12\x41\n\x0egemma_endpoint\x18\x06'
    b" \x01(\x0b\x32'.antigravity.localharness.GemmaEndpointH\x00\x12\x43\n\x0f\x63ustom_endpoint\x18\x07"
    b' \x01(\x0b\x32(.antigravity.localharness.CustomEndpointH\x00\x42\n\n\x08\x65ndpoint"!\n\rGemmaEndpoint\x12\x10\n\x08\x62\x61se_url\x18\x01'
    b' \x01(\t";\n\x0e\x43ustomEndpoint\x12\x14\n\x0c\x62\x61\x63kend_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02'
    b' \x01(\t"\xac\x01\n\x12SystemInstructions\x12\x44\n\x06\x63ustom\x18\x01'
    b' \x01(\x0b\x32\x32.antigravity.localharness.CustomSystemInstructionsH\x00\x12H\n\x08\x61ppended\x18\x02'
    b' \x01(\x0b\x32\x34.antigravity.localharness.AppendedSystemInstructionsH\x00\x42\x06\n\x04type"\x81\x01\n\x18\x43ustomSystemInstructions\x12\x45\n\x04part\x18\x01'
    b' \x03(\x0b\x32\x37.antigravity.localharness.CustomSystemInstructions.Part\x1a\x1e\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x42\x06\n\x04part"\xb9\x01\n\x1a\x41ppendedSystemInstructions\x12\x17\n\x0f\x63ustom_identity\x18\x01'
    b' \x01(\t\x12W\n\x11\x61ppended_sections\x18\x02'
    b' \x03(\x0b\x32<.antigravity.localharness.AppendedSystemInstructions.Section\x1a)\n\x07Section\x12\r\n\x05title\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02'
    b' \x01(\t"g\n\x04Tool\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x1e\n\x16parameters_json_schema\x18\x03'
    b' \x01(\t\x12\x1c\n\x14response_json_schema\x18\x04'
    b' \x01(\t"\xf7\x06\n\x10HarnessSideTools\x12\x36\n\x04\x66ind\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.FindToolConfig\x12\x43\n\x0brun_command\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.RunCommandToolConfig\x12<\n\tsubagents\x18\x03'
    b' \x01(\x0b\x32).antigravity.localharness.SubagentsConfig\x12\x45\n\x0euser_questions\x18\x04'
    b' \x01(\x0b\x32-.antigravity.localharness.UserQuestionsConfig\x12?\n\tfile_edit\x18\x05'
    b' \x01(\x0b\x32,.antigravity.localharness.FileEditToolConfig\x12?\n\tview_file\x18\x06'
    b' \x01(\x0b\x32,.antigravity.localharness.ViewFileToolConfig\x12\x46\n\rwrite_to_file\x18\x07'
    b' \x01(\x0b\x32/.antigravity.localharness.WriteToFileToolConfig\x12\x43\n\x0bgrep_search\x18\x08'
    b' \x01(\x0b\x32..antigravity.localharness.GrepSearchToolConfig\x12=\n\x08list_dir\x18\t'
    b' \x01(\x0b\x32+.antigravity.localharness.ListDirToolConfig\x12@\n\x0bpermissions\x18\n'
    b' \x01(\x0b\x32+.antigravity.localharness.PermissionsConfig\x12I\n\x0egenerate_image\x18\x0b'
    b' \x01(\x0b\x32\x31.antigravity.localharness.GenerateImageToolConfig\x12\x41\n\nsearch_web\x18\x0c'
    b' \x01(\x0b\x32-.antigravity.localharness.SearchWebToolConfig\x12\x43\n\x0b\x63ode_search\x18\r'
    b' \x01(\x0b\x32..antigravity.localharness.CodeSearchToolConfig"\xc4\x01\n\x14\x43odeSearchToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true\x12\x19\n\x11g3box_max_retries\x18\x02'
    b' \x01(\x05\x12\x1e\n\x16g3box_retry_backoff_ms\x18\x03'
    b' \x01(\x05\x12"\n\x1ag3box_max_retry_backoff_ms\x18\x04'
    b' \x01(\x05\x12\x18\n\x10g3box_timeout_ms\x18\x05'
    b' \x01(\x05\x12\x1c\n\x14g3box_rpc_timeout_ms\x18\x06'
    b' \x01(\x05"m\n\x0e\x46indToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true\x12\x17\n\x0fuse_code_search\x18\x02'
    b' \x01(\x08\x12+\n#disable_fallback_to_local_execution\x18\x03'
    b' \x01(\x08"-\n\x14RunCommandToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"(\n\x0fSubagentsConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true",\n\x13UserQuestionsConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"+\n\x12\x46ileEditToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"+\n\x12ViewFileToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true".\n\x15WriteToFileToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"s\n\x14GrepSearchToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true\x12\x17\n\x0fuse_code_search\x18\x02'
    b' \x01(\x08\x12+\n#disable_fallback_to_local_execution\x18\x03'
    b' \x01(\x08"*\n\x11ListDirToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"6\n\x17GenerateImageToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04trueJ\x04\x08\x02\x10\x03",\n\x13SearchWebToolConfig\x12\x15\n\x07\x65nabled\x18\x01'
    b' \x01(\x08:\x04true"9\n\x11PermissionsConfig\x12$\n\x1c\x65nforce_workspace_validation\x18\x01'
    b' \x01(\x08"-\n\x0cOutputConfig\x12\x0c\n\x04port\x18\x01'
    b' \x01(\x05\x12\x0f\n\x07\x61pi_key\x18\x02'
    b' \x01(\t"\xfa\x03\n\x0bOutputEvent\x12\x0f\n\x07seq_num\x18\x01'
    b' \x01(\x03\x12\x18\n\x10timestamp_micros\x18\x02'
    b' \x01(\x03\x12;\n\x0bstep_update\x18\n'
    b' \x01(\x0b\x32$.antigravity.localharness.StepUpdateH\x00\x12R\n\x17trajectory_state_update\x18\x0b'
    b' \x01(\x0b\x32/.antigravity.localharness.TrajectoryStateUpdateH\x00\x12\x37\n\ttool_call\x18\x0c'
    b' \x01(\x0b\x32".antigravity.localharness.ToolCallH\x00\x12\x64\n'
    b' initialize_conversation_response\x18\r'
    b' \x01(\x0b\x32\x38.antigravity.localharness.InitializeConversationResponseH\x00\x12\x46\n\x11\x63\x61ll_hook_request\x18\x0e'
    b' \x01(\x0b\x32).antigravity.localharness.CallHookRequestH\x00\x12?\n\x0eusage_metadata\x18\x14'
    b' \x01(\x0b\x32\'.antigravity.localharness.UsageMetadataB\x07\n\x05\x65vent"k\n\x1eInitializeConversationResponse\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x35\n\x07history\x18\x02'
    b' \x03(\x0b\x32$.antigravity.localharness.StepUpdate"\xc7\r\n\nStepUpdate\x12\x12\n\ncascade_id\x18\x01'
    b' \x01(\t\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x03 \x01(\r\x12\x39\n\x05state\x18\x04'
    b' \x01(\x0e\x32*.antigravity.localharness.StepUpdate.State\x12;\n\x06source\x18\x05'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Source\x12;\n\x06target\x18\x06'
    b' \x01(\x0e\x32+.antigravity.localharness.StepUpdate.Target\x12\x15\n\rerror_message\x18\x07'
    b' \x01(\t\x12\x10\n\x08thinking\x18\x08'
    b' \x01(\t\x12\x12\n\ntext_delta\x18\t'
    b' \x01(\t\x12\x16\n\x0ethinking_delta\x18\n'
    b' \x01(\t\x12\x0c\n\x04text\x18\x14'
    b' \x01(\t\x12\x45\n\x0elist_directory\x18\x15'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionListDirectory\x12;\n\tfind_file\x18\x16'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionFindFile\x12I\n\x10search_directory\x18\x17'
    b' \x01(\x0b\x32/.antigravity.localharness.ActionSearchDirectory\x12;\n\tview_file\x18\x18'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionViewFile\x12?\n\x0b\x63reate_file\x18\x19'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCreateFile\x12;\n\tedit_file\x18\x1a'
    b' \x01(\x0b\x32(.antigravity.localharness.ActionEditFile\x12?\n\x0brun_command\x18\x1b'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionRunCommand\x12>\n\ncompaction\x18\x1c'
    b' \x01(\x0b\x32*.antigravity.localharness.ActionCompaction\x12G\n\x0finvoke_subagent\x18\x1d'
    b' \x01(\x0b\x32..antigravity.localharness.ActionInvokeSubagent\x12\x45\n\x0egenerate_image\x18\x1e'
    b' \x01(\x0b\x32-.antigravity.localharness.ActionGenerateImage\x12\x36\n\x06\x66inish\x18\x1f'
    b' \x01(\x0b\x32&.antigravity.localharness.ActionFinish\x12\x34\n\x05\x65rror\x18'
    b'  \x01(\x0b\x32%.antigravity.localharness.ActionError\x12\x39\n\x08mcp_tool\x18!'
    b' \x01(\x0b\x32\'.antigravity.localharness.ActionMcpTool\x12=\n\nsearch_web\x18"'
    b' \x01(\x0b\x32).antigravity.localharness.ActionSearchWeb\x12\x14\n\x0crequest_text\x18\x32'
    b' \x01(\t\x12T\n\x19tool_confirmation_request\x18\x33'
    b' \x01(\x0b\x32\x31.antigravity.localharness.ToolConfirmationRequest\x12I\n\x11questions_request\x18\x34'
    b' \x01(\x0b\x32..antigravity.localharness.UserQuestionsRequest"s\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTATE_ACTIVE\x10\x01\x12\x0e\n\nSTATE_DONE\x10\x02\x12\x1a\n\x16STATE_WAITING_FOR_USER\x10\x03\x12\x0f\n\x0bSTATE_ERROR\x10\x04"\x04\x08\x05\x10\x05"V\n\x06Source\x12\x16\n\x12SOURCE_UNSPECIFIED\x10\x00\x12\x11\n\rSOURCE_SYSTEM\x10\x01\x12\x0f\n\x0bSOURCE_USER\x10\x02\x12\x10\n\x0cSOURCE_MODEL\x10\x03"[\n\x06Target\x12\x16\n\x12TARGET_UNSPECIFIED\x10\x00\x12\x0f\n\x0bTARGET_USER\x10\x01\x12\x10\n\x0cTARGET_MODEL\x10\x02\x12\x16\n\x12TARGET_ENVIRONMENT\x10\x03"d\n\x13\x41\x63tionGenerateImage\x12\x0e\n\x06prompt\x18\x01'
    b' \x01(\t\x12\x13\n\x0bimage_paths\x18\x02'
    b' \x03(\t\x12\x12\n\nimage_name\x18\x03'
    b' \x01(\t\x12\x14\n\x0c\x61spect_ratio\x18\x04'
    b' \x01(\t"A\n\x0f\x41\x63tionSearchWeb\x12\r\n\x05query\x18\x01'
    b' \x01(\t\x12\x0e\n\x06\x64omain\x18\x02'
    b' \x01(\t\x12\x0f\n\x07summary\x18\x03'
    b' \x01(\t"%\n\x0c\x41\x63tionFinish\x12\x15\n\routput_string\x18\x01'
    b' \x01(\t"7\n\x0b\x41\x63tionError\x12\x15\n\rerror_message\x18\x01'
    b' \x01(\t\x12\x11\n\thttp_code\x18\x02'
    b' \x01(\r"\xc1\x01\n\x13\x41\x63tionListDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\x45\n\x07results\x18\x02'
    b' \x03(\x0b\x32\x34.antigravity.localharness.ActionListDirectory.Result\x1aK\n\x06Result\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x16\n\x0cis_directory\x18\x02'
    b' \x01(\x08H\x00\x12\x13\n\tfile_size\x18\x03'
    b' \x01(\x04H\x00\x42\x06\n\x04info"G\n\x0e\x41\x63tionFindFile\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03'
    b' \x01(\t"S\n\x15\x41\x63tionSearchDirectory\x12\x16\n\x0e\x64irectory_path\x18\x01'
    b' \x01(\t\x12\r\n\x05query\x18\x02'
    b' \x01(\t\x12\x13\n\x0bnum_results\x18\x03'
    b' \x01(\x05"I\n\x0e\x41\x63tionViewFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x12\n\nstart_line\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x65nd_line\x18\x03'
    b' \x01(\r"7\n\x10\x41\x63tionCreateFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x10\n\x08\x63ontents\x18\x02'
    b' \x01(\t"\xba\x03\n\x0e\x41\x63tionEditFile\x12\x11\n\tfile_path\x18\x01'
    b' \x01(\t\x12\x46\n\ndiff_block\x18\x02'
    b' \x03(\x0b\x32\x32.antigravity.localharness.ActionEditFile.DiffBlock\x1a\xd7\x01\n\x08\x44iffLine\x12\x0c\n\x04text\x18\x01'
    b' \x01(\t\x12L\n\x06\x61\x63tion\x18\x02'
    b' \x01(\x0e\x32<.antigravity.localharness.ActionEditFile.DiffLine.LineAction"o\n\nLineAction\x12\x1b\n\x17LINE_ACTION_UNSPECIFIED\x10\x00\x12\x16\n\x12LINE_ACTION_INSERT\x10\x01\x12\x16\n\x12LINE_ACTION_DELETE\x10\x02\x12\x14\n\x10LINE_ACTION_NONE\x10\x03\x1as\n\tDiffBlock\x12\x12\n\nstart_line\x18\x01'
    b' \x01(\x05\x12\x10\n\x08\x65nd_line\x18\x02'
    b' \x01(\x05\x12@\n\x05lines\x18\x03'
    b' \x03(\x0b\x32\x31.antigravity.localharness.ActionEditFile.DiffLine"i\n\x10\x41\x63tionRunCommand\x12\x14\n\x0c\x63ommand_line\x18\x01'
    b' \x01(\t\x12\x13\n\x0bworking_dir\x18\x02'
    b' \x01(\t\x12\x11\n\texit_code\x18\x04'
    b' \x01(\x05\x12\x17\n\x0f\x63ombined_output\x18\x05'
    b' \x01(\t"\x12\n\x10\x41\x63tionCompaction"\x16\n\x14\x41\x63tionInvokeSubagent"\x19\n\x17ToolConfirmationRequest"Q\n\x14UserQuestionsRequest\x12\x39\n\tquestions\x18\x01'
    b' \x03(\x0b\x32&.antigravity.localharness.UserQuestion"d\n\x0cUserQuestion\x12\x43\n\x0fmultiple_choice\x18\x01'
    b' \x01(\x0b\x32(.antigravity.localharness.MultipleChoiceH\x00\x42\x0f\n\rquestion_type"L\n\x0eMultipleChoice\x12\x10\n\x08question\x18\x01'
    b' \x01(\t\x12\x0f\n\x07\x63hoices\x18\x02'
    b' \x03(\t\x12\x17\n\x0fis_multi_select\x18\x03'
    b' \x01(\x08"\xc5\x03\n\nInputEvent\x12\x14\n\nuser_input\x18\x01'
    b' \x01(\tH\x00\x12\x41\n\x12\x63omplex_user_input\x18\x07'
    b' \x01(\x0b\x32#.antigravity.localharness.UserInputH\x00\x12G\n\x11tool_confirmation\x18\x02'
    b' \x01(\x0b\x32*.antigravity.localharness.ToolConfirmationH\x00\x12?\n\rtool_response\x18\x03'
    b' \x01(\x0b\x32&.antigravity.localharness.ToolResponseH\x00\x12L\n\x11question_response\x18\x04'
    b' \x01(\x0b\x32/.antigravity.localharness.UserQuestionsResponseH\x00\x12\x16\n\x0chalt_request\x18\x05'
    b' \x01(\x08H\x00\x12\x1b\n\x11\x61utomated_trigger\x18\x06'
    b' \x01(\tH\x00\x12H\n\x12\x63\x61ll_hook_response\x18\x08'
    b' \x01(\x0b\x32*.antigravity.localharness.CallHookResponseH\x00\x42\x07\n\x05\x65vent"\xc9\x02\n\tUserInput\x12\x37\n\x05parts\x18\x01'
    b' \x03(\x0b\x32(.antigravity.localharness.UserInput.Part\x1a=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c\x1a\x1c\n\x0cSlashCommand\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x1a\xa5\x01\n\x04Part\x12\x0e\n\x04text\x18\x01'
    b' \x01(\tH\x00\x12:\n\x05media\x18\x02'
    b' \x01(\x0b\x32).antigravity.localharness.UserInput.MediaH\x00\x12I\n\rslash_command\x18\x03'
    b' \x01(\x0b\x32\x30.antigravity.localharness.UserInput.SlashCommandH\x00\x42\x06\n\x04part"O\n\x10ToolConfirmation\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03'
    b' \x01(\x08"\xc6\x01\n\x15TrajectoryStateUpdate\x12\x15\n\rtrajectory_id\x18\x02'
    b' \x01(\t\x12\x44\n\x05state\x18\x03'
    b' \x01(\x0e\x32\x35.antigravity.localharness.TrajectoryStateUpdate.State\x12\r\n\x05\x65rror\x18\x04'
    b' \x01(\t"A\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n\rSTATE_RUNNING\x10\x01\x12\x0e\n\nSTATE_IDLE\x10\x02"9\n\x06Struct\x12/\n\x06\x66ields\x18\x01'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Field"E\n\x05\x46ield\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12.\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x1f.antigravity.localharness.Value"\xb7\x02\n\x05Value\x12\x39\n\nnull_value\x18\x01'
    b' \x01(\x0e\x32#.antigravity.localharness.NullValueH\x00\x12\x16\n\x0cnumber_value\x18\x02'
    b' \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03'
    b' \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04'
    b' \x01(\x08H\x00\x12\x38\n\x0cstruct_value\x18\x05 \x01(\x0b\x32'
    b' .antigravity.localharness.StructH\x00\x12\x39\n\nlist_value\x18\x06'
    b' \x01(\x0b\x32#.antigravity.localharness.ListValueH\x00\x12\x30\n\x05media\x18\x07'
    b' \x01(\x0b\x32\x1f.antigravity.localharness.MediaH\x00\x42\x06\n\x04kind"<\n\tListValue\x12/\n\x06values\x18\x01'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Value"q\n\x08ToolCall\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04name\x18\x02'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03'
    b' \x01(\t\x12\x33\n\targuments\x18\x04 \x01(\x0b\x32'
    b' .antigravity.localharness.Struct"\xa2\x01\n\x0cToolResponse\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x15\n\rresponse_json\x18\x02'
    b' \x01(\t\x12;\n\x12supplemental_media\x18\x03'
    b' \x03(\x0b\x32\x1f.antigravity.localharness.Media\x12\x32\n\x08response\x18\x04'
    b' \x01(\x0b\x32'
    b' .antigravity.localharness.Struct"\x8c\x02\n\x15UserQuestionsResponse\x12\x15\n\rtrajectory_id\x18\x01'
    b' \x01(\t\x12\x12\n\nstep_index\x18\x02'
    b' \x01(\r\x12\x13\n\tcancelled\x18\x03'
    b' \x01(\x08H\x00\x12U\n\x08response\x18\x04'
    b' \x01(\x0b\x32\x41.antigravity.localharness.UserQuestionsResponse.QuestionsResponseH\x00\x1aR\n\x11QuestionsResponse\x12=\n\x07\x61nswers\x18\x01'
    b' \x03(\x0b\x32,.antigravity.localharness.UserQuestionAnswerB\x08\n\x06result"\x86\x01\n\x12UserQuestionAnswer\x12\x14\n\nunanswered\x18\x01'
    b' \x01(\x08H\x00\x12P\n\x16multiple_choice_answer\x18\x02'
    b' \x01(\x0b\x32..antigravity.localharness.MultipleChoiceAnswerH\x00\x42\x08\n\x06\x61nswer"R\n\x14MultipleChoiceAnswer\x12\x1f\n\x17selected_choice_indices\x18\x01'
    b' \x03(\x05\x12\x19\n\x11\x66reeform_response\x18\x02'
    b' \x01(\t"=\n\x05Media\x12\x11\n\tmime_type\x18\x01'
    b' \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03'
    b' \x01(\x0c"\xa8\x01\n\rUsageMetadata\x12\x1a\n\x12prompt_token_count\x18\x01'
    b' \x01(\x04\x12"\n\x1a\x63\x61\x63hed_content_token_count\x18\x05'
    b' \x01(\x04\x12\x1e\n\x16\x63\x61ndidates_token_count\x18\x02'
    b' \x01(\x04\x12\x1c\n\x14thoughts_token_count\x18\x04'
    b' \x01(\x04\x12\x19\n\x11total_token_count\x18\x03'
    b' \x01(\x04"\xa9\x03\n\x0fMcpServerConfig\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12<\n\x05stdio\x18\x02'
    b' \x01(\x0b\x32+.antigravity.localharness.McpStdioTransportH\x00\x12:\n\x04http\x18\x03'
    b' \x01(\x0b\x32*.antigravity.localharness.McpHttpTransportH\x00\x12\x15\n\renabled_tools\x18\x04'
    b' \x03(\t\x12\x16\n\x0e\x64isabled_tools\x18\x05'
    b' \x03(\t\x12V\n\x12\x61uth_provider_type\x18\x06'
    b' \x01(\x0e\x32:.antigravity.localharness.McpServerConfig.AuthProviderType\x12\x17\n\x0ftimeout_seconds\x18\x07'
    b' \x01(\x05"a\n\x10\x41uthProviderType\x12"\n\x1e\x41UTH_PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12)\n%AUTH_PROVIDER_TYPE_GOOGLE_CREDENTIALS\x10\x01\x42\x0b\n\ttransport"\xa1\x01\n\x11McpStdioTransport\x12\x0f\n\x07\x63ommand\x18\x01'
    b' \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12\x41\n\x03\x65nv\x18\x03'
    b' \x03(\x0b\x32\x34.antigravity.localharness.McpStdioTransport.EnvEntry\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"\x99\x01\n\x10McpHttpTransport\x12\x0b\n\x03url\x18\x01'
    b' \x01(\t\x12H\n\x07headers\x18\x02'
    b' \x03(\x0b\x32\x37.antigravity.localharness.McpHttpTransport.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12\r\n\x05value\x18\x02'
    b' \x01(\t:\x02\x38\x01"O\n\rActionMcpTool\x12\x13\n\x0bserver_name\x18\x01'
    b' \x01(\t\x12\x11\n\ttool_name\x18\x02'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03'
    b' \x01(\t"\xf6\x02\n\x0f\x43\x61llHookRequest\x12\x12\n\nrequest_id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x35\n\x04type\x18\x07'
    b" \x01(\x0e\x32'.antigravity.localharness.LifecycleHook\x12>\n\rpre_turn_args\x18\x03"
    b' \x01(\x0b\x32%.antigravity.localharness.PreTurnArgsH\x00\x12@\n\x0epost_turn_args\x18\x04'
    b' \x01(\x0b\x32&.antigravity.localharness.PostTurnArgsH\x00\x12>\n\rpre_tool_args\x18\x05'
    b' \x01(\x0b\x32%.antigravity.localharness.PreToolArgsH\x00\x12@\n\x0epost_tool_args\x18\x06'
    b' \x01(\x0b\x32&.antigravity.localharness.PostToolArgsH\x00\x42\x06\n\x04\x61rgs"\x90\x02\n\x10\x43\x61llHookResponse\x12\x12\n\nrequest_id\x18\x01'
    b' \x01(\t\x12\x42\n\x0fpre_turn_result\x18\x02'
    b" \x01(\x0b\x32'.antigravity.localharness.PreTurnResultH\x00\x12\x42\n\x0fpre_tool_result\x18\x03"
    b" \x01(\x0b\x32'.antigravity.localharness.PreToolResultH\x00\x12=\n\x0c\x65mpty_result\x18\x04"
    b' \x01(\x0b\x32%.antigravity.localharness.EmptyResultH\x00\x12\x17\n\rerror_message\x18\x05'
    b' \x01(\tH\x00\x42\x08\n\x06result"8\n\x0bPreToolArgs\x12\x11\n\ttool_name\x18\x01'
    b' \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02'
    b' \x01(\t"@\n\x0cPostToolArgs\x12\x11\n\ttool_name\x18\x01'
    b' \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03'
    b' \x01(\t"F\n\x0bPreTurnArgs\x12\x37\n\nuser_input\x18\x01'
    b' \x01(\x0b\x32#.antigravity.localharness.UserInput"%\n\x0cPostTurnArgs\x12\x15\n\rresponse_text\x18\x01'
    b' \x01(\t"\r\n\x0b\x45mptyResult"\x9e\x01\n\rPreToolResult\x12\x42\n\x08\x64\x65\x63ision\x18\x01'
    b' \x01(\x0e\x32\x30.antigravity.localharness.PreToolResult.Decision\x12\x0e\n\x06reason\x18\x02'
    b' \x01(\t"9\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\x08\n\x04\x44\x45NY\x10\x02"\x9e\x01\n\rPreTurnResult\x12\x42\n\x08\x64\x65\x63ision\x18\x01'
    b' \x01(\x0e\x32\x30.antigravity.localharness.PreTurnResult.Decision\x12\x0e\n\x06reason\x18\x02'
    b' \x01(\t"9\n\x08\x44\x65\x63ision\x12\x18\n\x14\x44\x45\x43ISION_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\x08\n\x04\x44\x45NY\x10\x02*\x8f\x02\n\rLifecycleHook\x12\x1e\n\x1aLIFECYCLE_HOOK_UNSPECIFIED\x10\x00\x12#\n\x1fLIFECYCLE_HOOK_ON_SESSION_START\x10\x01\x12!\n\x1dLIFECYCLE_HOOK_ON_SESSION_END\x10\x02\x12\x1b\n\x17LIFECYCLE_HOOK_PRE_TURN\x10\x03\x12\x1c\n\x18LIFECYCLE_HOOK_POST_TURN\x10\x04\x12\x1b\n\x17LIFECYCLE_HOOK_PRE_TOOL\x10\x05\x12\x1c\n\x18LIFECYCLE_HOOK_POST_TOOL\x10\x06\x12'
    b' \n\x1cLIFECYCLE_HOOK_ON_TOOL_ERROR\x10\x07*R\n\tModelType\x12\x1a\n\x16MODEL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fMODEL_TYPE_TEXT\x10\x01\x12\x14\n\x10MODEL_TYPE_IMAGE\x10\x02*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x62\x08\x65\x64itionsp\xe9\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'localharness_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._loaded_options = None
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._loaded_options = None
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._loaded_options = None
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._serialized_options = b'8\001'
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._loaded_options = None
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_LIFECYCLEHOOK']._serialized_start = 13249
  _globals['_LIFECYCLEHOOK']._serialized_end = 13520
  _globals['_MODELTYPE']._serialized_start = 13522
  _globals['_MODELTYPE']._serialized_end = 13604
  _globals['_NULLVALUE']._serialized_start = 13606
  _globals['_NULLVALUE']._serialized_end = 13633
  _globals['_INPUTCONFIG']._serialized_start = 49
  _globals['_INPUTCONFIG']._serialized_end = 195
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_start = 197
  _globals['_INITIALIZECONVERSATIONEVENT']._serialized_end = 283
  _globals['_CLIENTINFO']._serialized_start = 285
  _globals['_CLIENTINFO']._serialized_end = 358
  _globals['_HARNESSCONFIG']._serialized_start = 361
  _globals['_HARNESSCONFIG']._serialized_end = 983
  _globals['_WORKSPACE']._serialized_start = 985
  _globals['_WORKSPACE']._serialized_end = 1093
  _globals['_FILESYSTEMWORKSPACE']._serialized_start = 1095
  _globals['_FILESYSTEMWORKSPACE']._serialized_end = 1135
  _globals['_GEMINIMODELOPTIONS']._serialized_start = 1137
  _globals['_GEMINIMODELOPTIONS']._serialized_end = 1181
  _globals['_GEMINIAPIENDPOINT']._serialized_start = 1184
  _globals['_GEMINIAPIENDPOINT']._serialized_end = 1437
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._serialized_start = 1387
  _globals['_GEMINIAPIENDPOINT_HTTPHEADERSENTRY']._serialized_end = 1437
  _globals['_VERTEXENDPOINT']._serialized_start = 1440
  _globals['_VERTEXENDPOINT']._serialized_end = 1705
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._serialized_start = 1387
  _globals['_VERTEXENDPOINT_HTTPHEADERSENTRY']._serialized_end = 1437
  _globals['_MODELCONFIG']._serialized_start = 1708
  _globals['_MODELCONFIG']._serialized_end = 2080
  _globals['_GEMMAENDPOINT']._serialized_start = 2082
  _globals['_GEMMAENDPOINT']._serialized_end = 2115
  _globals['_CUSTOMENDPOINT']._serialized_start = 2117
  _globals['_CUSTOMENDPOINT']._serialized_end = 2176
  _globals['_SYSTEMINSTRUCTIONS']._serialized_start = 2179
  _globals['_SYSTEMINSTRUCTIONS']._serialized_end = 2351
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_start = 2354
  _globals['_CUSTOMSYSTEMINSTRUCTIONS']._serialized_end = 2483
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_start = 2453
  _globals['_CUSTOMSYSTEMINSTRUCTIONS_PART']._serialized_end = 2483
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_start = 2486
  _globals['_APPENDEDSYSTEMINSTRUCTIONS']._serialized_end = 2671
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_start = 2630
  _globals['_APPENDEDSYSTEMINSTRUCTIONS_SECTION']._serialized_end = 2671
  _globals['_TOOL']._serialized_start = 2673
  _globals['_TOOL']._serialized_end = 2776
  _globals['_HARNESSSIDETOOLS']._serialized_start = 2779
  _globals['_HARNESSSIDETOOLS']._serialized_end = 3666
  _globals['_CODESEARCHTOOLCONFIG']._serialized_start = 3669
  _globals['_CODESEARCHTOOLCONFIG']._serialized_end = 3865
  _globals['_FINDTOOLCONFIG']._serialized_start = 3867
  _globals['_FINDTOOLCONFIG']._serialized_end = 3976
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_start = 3978
  _globals['_RUNCOMMANDTOOLCONFIG']._serialized_end = 4023
  _globals['_SUBAGENTSCONFIG']._serialized_start = 4025
  _globals['_SUBAGENTSCONFIG']._serialized_end = 4065
  _globals['_USERQUESTIONSCONFIG']._serialized_start = 4067
  _globals['_USERQUESTIONSCONFIG']._serialized_end = 4111
  _globals['_FILEEDITTOOLCONFIG']._serialized_start = 4113
  _globals['_FILEEDITTOOLCONFIG']._serialized_end = 4156
  _globals['_VIEWFILETOOLCONFIG']._serialized_start = 4158
  _globals['_VIEWFILETOOLCONFIG']._serialized_end = 4201
  _globals['_WRITETOFILETOOLCONFIG']._serialized_start = 4203
  _globals['_WRITETOFILETOOLCONFIG']._serialized_end = 4249
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_start = 4251
  _globals['_GREPSEARCHTOOLCONFIG']._serialized_end = 4366
  _globals['_LISTDIRTOOLCONFIG']._serialized_start = 4368
  _globals['_LISTDIRTOOLCONFIG']._serialized_end = 4410
  _globals['_GENERATEIMAGETOOLCONFIG']._serialized_start = 4412
  _globals['_GENERATEIMAGETOOLCONFIG']._serialized_end = 4466
  _globals['_SEARCHWEBTOOLCONFIG']._serialized_start = 4468
  _globals['_SEARCHWEBTOOLCONFIG']._serialized_end = 4512
  _globals['_PERMISSIONSCONFIG']._serialized_start = 4514
  _globals['_PERMISSIONSCONFIG']._serialized_end = 4571
  _globals['_OUTPUTCONFIG']._serialized_start = 4573
  _globals['_OUTPUTCONFIG']._serialized_end = 4618
  _globals['_OUTPUTEVENT']._serialized_start = 4621
  _globals['_OUTPUTEVENT']._serialized_end = 5127
  _globals['_INITIALIZECONVERSATIONRESPONSE']._serialized_start = 5129
  _globals['_INITIALIZECONVERSATIONRESPONSE']._serialized_end = 5236
  _globals['_STEPUPDATE']._serialized_start = 5239
  _globals['_STEPUPDATE']._serialized_end = 6974
  _globals['_STEPUPDATE_STATE']._serialized_start = 6678
  _globals['_STEPUPDATE_STATE']._serialized_end = 6793
  _globals['_STEPUPDATE_SOURCE']._serialized_start = 6795
  _globals['_STEPUPDATE_SOURCE']._serialized_end = 6881
  _globals['_STEPUPDATE_TARGET']._serialized_start = 6883
  _globals['_STEPUPDATE_TARGET']._serialized_end = 6974
  _globals['_ACTIONGENERATEIMAGE']._serialized_start = 6976
  _globals['_ACTIONGENERATEIMAGE']._serialized_end = 7076
  _globals['_ACTIONSEARCHWEB']._serialized_start = 7078
  _globals['_ACTIONSEARCHWEB']._serialized_end = 7143
  _globals['_ACTIONFINISH']._serialized_start = 7145
  _globals['_ACTIONFINISH']._serialized_end = 7182
  _globals['_ACTIONERROR']._serialized_start = 7184
  _globals['_ACTIONERROR']._serialized_end = 7239
  _globals['_ACTIONLISTDIRECTORY']._serialized_start = 7242
  _globals['_ACTIONLISTDIRECTORY']._serialized_end = 7435
  _globals['_ACTIONLISTDIRECTORY_RESULT']._serialized_start = 7360
  _globals['_ACTIONLISTDIRECTORY_RESULT']._serialized_end = 7435
  _globals['_ACTIONFINDFILE']._serialized_start = 7437
  _globals['_ACTIONFINDFILE']._serialized_end = 7508
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_start = 7510
  _globals['_ACTIONSEARCHDIRECTORY']._serialized_end = 7593
  _globals['_ACTIONVIEWFILE']._serialized_start = 7595
  _globals['_ACTIONVIEWFILE']._serialized_end = 7668
  _globals['_ACTIONCREATEFILE']._serialized_start = 7670
  _globals['_ACTIONCREATEFILE']._serialized_end = 7725
  _globals['_ACTIONEDITFILE']._serialized_start = 7728
  _globals['_ACTIONEDITFILE']._serialized_end = 8170
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_start = 7838
  _globals['_ACTIONEDITFILE_DIFFLINE']._serialized_end = 8053
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_start = 7942
  _globals['_ACTIONEDITFILE_DIFFLINE_LINEACTION']._serialized_end = 8053
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_start = 8055
  _globals['_ACTIONEDITFILE_DIFFBLOCK']._serialized_end = 8170
  _globals['_ACTIONRUNCOMMAND']._serialized_start = 8172
  _globals['_ACTIONRUNCOMMAND']._serialized_end = 8277
  _globals['_ACTIONCOMPACTION']._serialized_start = 8279
  _globals['_ACTIONCOMPACTION']._serialized_end = 8297
  _globals['_ACTIONINVOKESUBAGENT']._serialized_start = 8299
  _globals['_ACTIONINVOKESUBAGENT']._serialized_end = 8321
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_start = 8323
  _globals['_TOOLCONFIRMATIONREQUEST']._serialized_end = 8348
  _globals['_USERQUESTIONSREQUEST']._serialized_start = 8350
  _globals['_USERQUESTIONSREQUEST']._serialized_end = 8431
  _globals['_USERQUESTION']._serialized_start = 8433
  _globals['_USERQUESTION']._serialized_end = 8533
  _globals['_MULTIPLECHOICE']._serialized_start = 8535
  _globals['_MULTIPLECHOICE']._serialized_end = 8611
  _globals['_INPUTEVENT']._serialized_start = 8614
  _globals['_INPUTEVENT']._serialized_end = 9067
  _globals['_USERINPUT']._serialized_start = 9070
  _globals['_USERINPUT']._serialized_end = 9399
  _globals['_USERINPUT_MEDIA']._serialized_start = 9140
  _globals['_USERINPUT_MEDIA']._serialized_end = 9201
  _globals['_USERINPUT_SLASHCOMMAND']._serialized_start = 9203
  _globals['_USERINPUT_SLASHCOMMAND']._serialized_end = 9231
  _globals['_USERINPUT_PART']._serialized_start = 9234
  _globals['_USERINPUT_PART']._serialized_end = 9399
  _globals['_TOOLCONFIRMATION']._serialized_start = 9401
  _globals['_TOOLCONFIRMATION']._serialized_end = 9480
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_start = 9483
  _globals['_TRAJECTORYSTATEUPDATE']._serialized_end = 9681
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_start = 9616
  _globals['_TRAJECTORYSTATEUPDATE_STATE']._serialized_end = 9681
  _globals['_STRUCT']._serialized_start = 9683
  _globals['_STRUCT']._serialized_end = 9740
  _globals['_FIELD']._serialized_start = 9742
  _globals['_FIELD']._serialized_end = 9811
  _globals['_VALUE']._serialized_start = 9814
  _globals['_VALUE']._serialized_end = 10125
  _globals['_LISTVALUE']._serialized_start = 10127
  _globals['_LISTVALUE']._serialized_end = 10187
  _globals['_TOOLCALL']._serialized_start = 10189
  _globals['_TOOLCALL']._serialized_end = 10302
  _globals['_TOOLRESPONSE']._serialized_start = 10305
  _globals['_TOOLRESPONSE']._serialized_end = 10467
  _globals['_USERQUESTIONSRESPONSE']._serialized_start = 10470
  _globals['_USERQUESTIONSRESPONSE']._serialized_end = 10738
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_start = 10646
  _globals['_USERQUESTIONSRESPONSE_QUESTIONSRESPONSE']._serialized_end = 10728
  _globals['_USERQUESTIONANSWER']._serialized_start = 10741
  _globals['_USERQUESTIONANSWER']._serialized_end = 10875
  _globals['_MULTIPLECHOICEANSWER']._serialized_start = 10877
  _globals['_MULTIPLECHOICEANSWER']._serialized_end = 10959
  _globals['_MEDIA']._serialized_start = 9140
  _globals['_MEDIA']._serialized_end = 9201
  _globals['_USAGEMETADATA']._serialized_start = 11025
  _globals['_USAGEMETADATA']._serialized_end = 11193
  _globals['_MCPSERVERCONFIG']._serialized_start = 11196
  _globals['_MCPSERVERCONFIG']._serialized_end = 11621
  _globals['_MCPSERVERCONFIG_AUTHPROVIDERTYPE']._serialized_start = 11511
  _globals['_MCPSERVERCONFIG_AUTHPROVIDERTYPE']._serialized_end = 11608
  _globals['_MCPSTDIOTRANSPORT']._serialized_start = 11624
  _globals['_MCPSTDIOTRANSPORT']._serialized_end = 11785
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._serialized_start = 11743
  _globals['_MCPSTDIOTRANSPORT_ENVENTRY']._serialized_end = 11785
  _globals['_MCPHTTPTRANSPORT']._serialized_start = 11788
  _globals['_MCPHTTPTRANSPORT']._serialized_end = 11941
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._serialized_start = 11895
  _globals['_MCPHTTPTRANSPORT_HEADERSENTRY']._serialized_end = 11941
  _globals['_ACTIONMCPTOOL']._serialized_start = 11943
  _globals['_ACTIONMCPTOOL']._serialized_end = 12022
  _globals['_CALLHOOKREQUEST']._serialized_start = 12025
  _globals['_CALLHOOKREQUEST']._serialized_end = 12399
  _globals['_CALLHOOKRESPONSE']._serialized_start = 12402
  _globals['_CALLHOOKRESPONSE']._serialized_end = 12674
  _globals['_PRETOOLARGS']._serialized_start = 12676
  _globals['_PRETOOLARGS']._serialized_end = 12732
  _globals['_POSTTOOLARGS']._serialized_start = 12734
  _globals['_POSTTOOLARGS']._serialized_end = 12798
  _globals['_PRETURNARGS']._serialized_start = 12800
  _globals['_PRETURNARGS']._serialized_end = 12870
  _globals['_POSTTURNARGS']._serialized_start = 12872
  _globals['_POSTTURNARGS']._serialized_end = 12909
  _globals['_EMPTYRESULT']._serialized_start = 12911
  _globals['_EMPTYRESULT']._serialized_end = 12924
  _globals['_PRETOOLRESULT']._serialized_start = 12927
  _globals['_PRETOOLRESULT']._serialized_end = 13085
  _globals['_PRETOOLRESULT_DECISION']._serialized_start = 13028
  _globals['_PRETOOLRESULT_DECISION']._serialized_end = 13085
  _globals['_PRETURNRESULT']._serialized_start = 13088
  _globals['_PRETURNRESULT']._serialized_end = 13246
  _globals['_PRETURNRESULT_DECISION']._serialized_start = 13028
  _globals['_PRETURNRESULT_DECISION']._serialized_end = 13085
# @@protoc_insertion_point(module_scope)
